-- راه‌اندازی نسخه واقعی چت «پیوند» در Supabase
create table if not exists public.chat_messages (
 id bigint generated by default as identity primary key,
 room text not null default 'nimboluk',
 name text not null,
 employee text not null,
 message text not null,
 created_at timestamptz not null default now()
);
alter table public.chat_messages enable row level security;
create policy "chat read" on public.chat_messages for select to anon using (room='nimboluk');
create policy "chat insert" on public.chat_messages for insert to anon with check (room='nimboluk');
alter publication supabase_realtime add table public.chat_messages;